### ISSUE TITLE
symfony4.1 install faild

### ISSUE THREAD

**Issue by wukchao** [wasinger/jsonrpc-bundle#23]
- symfony/symfony v4.1.0 conflicts with __root__[No version set (parsed as 1.0.0)].
    - symfony/symfony v4.1.1 conflicts with __root__[No version set (parsed as 1.0.0)].
    - Installation request for wa72/jsonrpc-bundle ^0.6.1 -> satisfiable by wa72/jsonrpc-bundle[v0.6.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by ChristianVermeulen** [comment]
This happens when you use Flex. Because Flex wants you to use all symfony components independendly instead if installing the symfony/symfony framework all together. When you check you `composer.json` you'll find:

```
"conflict": {
    "symfony/symfony": "*"
},
```

**Comment by mnugter** [comment]
I created a PR with a small change in composer.json. Can you consider merging that PR to support Flex  & Symfony 4.x?

#24

**Comment by mnugter** [comment]
PR is merged, thanks!

So I think this issue can be closed then?
